$word = New-Object -ComObject Word.Application
$word.Visible = $false
$doc = $word.Documents.Open('e:\Vishruth Reports\Astral_Coatings_Dealer_Relationship_Report_11_expanded.docx')

$replacements = @{
    "The Indian paint industry is one of the fastest-growing sectors" = "The Indian coatings and paints sector stands out as a rapidly expanding segment of the national economy. This acceleration is primarily fueled by continuous infrastructure initiatives, booming real estate investments, escalating disposable incomes, and widespread urbanization. The market is generally split into two distinct classifications: industrial coatings and decorative paints. Accounting for nearly three-quarters (75%) of the overall market, the decorative segment encompasses putties, primers, enamels, and emulsions utilized in both commercial and residential buildings. The remaining quarter (25%) comprises the industrial sector, which includes powder coatings, marine finishes, and automotive paints essential for heavy machinery and infrastructure projects."
    "The Indian paint industry is highly consolidated, with a few organized national players" = "A handful of major national corporations currently dominate this highly consolidated industry. Prominent legacy players include AkzoNobel, Kansai Nerolac, Berger Paints, and Asian Paints. Recently, the competitive landscape has intensified with the introduction of formidable conglomerates like JSW Paints and Grasim Industries (operating as Birla Opus). To succeed in this fierce environment, companies cannot rely exclusively on brand recognition or product excellence; they must cultivate an extensive and resilient network of retail dealers. Because consumers often rely on the expertise of local painters and dealers to make purchasing decisions, these retail partners act as a vital bridge between the manufacturer and the end-user. Consequently, effective dealer relationship management has emerged as a fundamental strategy for capturing market share."
    "With the transition from traditional dry paint formulations to automated color mixing machines" = "The role of the traditional paint dealer has evolved significantly, particularly with the shift away from pre-mixed dry paints toward sophisticated in-store color tinting machines. Today's retail partners function as value-added consultants, utilizing automated tinting systems to blend colorants and base paints on demand, offering limitless customization. To empower these dealers, manufacturers provide comprehensive support, including volume-based discounts, flexible credit terms, and the physical installation of tinting equipment. Ultimately, Dealer Relationship Management (DRM) strategies are designed to harmonize the manufacturer's goals with the dealer's financial objectives, fostering long-term brand loyalty and maximizing sales efficiency."
    "The growth of the paint and coatings industry in India is supported by structural" = "The continuous expansion of the coatings industry in India is anchored in evolving demographic behaviors and macroeconomic changes. The primary catalysts stimulating demand include:"
    "Real Estate Expansion: Rapid urbanization and housing" = "Real Estate Booms: The surge in housing developments and urban expansion acts as the primary engine for decorative paint consumption."
    "Shorter Repainting Cycles: Rising disposable incomes and changing" = "Accelerated Repainting Intervals: Improved living standards and rising incomes have compressed the traditional 8-to-10-year repainting cycle down to just 4-to-5 years."
    "Automotive & Industrial Growth: Increased automotive production" = "Industrial & Auto Expansion: Massive investments in public infrastructure and automotive manufacturing directly boost the industrial coatings segment."
    "Digitalization of Channels: Paint manufacturers utilize mobile" = "Channel Digitalization: Manufacturers are increasingly adopting B2B e-commerce portals and mobile applications to optimize supply chains and facilitate seamless retail transactions."
    
    "The distribution and logistics network in the Indian paint industry has undergone a radical transformation" = "Over the last fifty years, the logistics and distribution framework of the Indian paint sector has experienced a dramatic metamorphosis. In the past, paint distribution relied on highly localized, disjointed trading webs. Manufacturers depended on complex, multi-level structures involving independent retail shops, regional stockists, and wholesalers. During this 'Local Shop Era' (prior to the 1990s), manufacturers had little control over retail pricing, brand loyalty was virtually non-existent, and technical assistance was rare. Retailers primarily stocked raw materials like cement paints, dry distempers, and linseed oils, acting as the ultimate authority for consumer choices."
    "During the 1990s and early 2010s, organized national brands led by Asian Paints" = "The transition into the 'Structured Dealer Network' era occurred throughout the 1990s and early 2010s, spearheaded by organized giants like Kansai Nerolac, Berger, and Asian Paints. The defining innovation of this period was the deployment of computerized color-mixing machines directly at retail storefronts. Instead of distributing thousands of distinct, pre-tinted paint buckets, manufacturers began shipping neutral base formulations alongside specialized liquid colorants. This breakthrough drastically minimized the inventory burden on dealers and shifted the basis of competition toward rapid delivery and limitless shade customization. Supply chains were modernized to ship products straight to authorized dealers from regional hubs within 48 hours, effectively eliminating the need for traditional wholesalers."
    "The period between 2010 and 2023 marked the 'Painter-Centric" = "From 2010 to 2023, the industry entered the 'Painter-Centric and Tech-Enabled Shift.' Manufacturers recognized that while dealers physically stock the product, professional contractors and painters hold the true power of recommendation. This realization led to the digitization of trade loyalty initiatives, enabling painters to instantly redeem cash rewards via mobile apps by scanning QR codes on product packaging. Today (2024 and beyond), the industry operates in the 'Tech-Enabled Partner' phase. This modern landscape is defined by digital color visualizers for consumers, automated credit settlements, real-time logistics tracking, and localized B2B ordering apps."
    
    "The global paints and coatings market size was valued at approximately USD 185 billion" = "By the year 2025, the global coatings and paints market achieved an estimated valuation of USD 185 billion, with forecasts suggesting a Compound Annual Growth Rate (CAGR) of 4.5% leading up to 2032. This worldwide momentum is largely fueled by surging demand for protective industrial coatings in the marine and aerospace sectors, extensive infrastructure renovations across Western Europe and North America, and massive construction booms in developing nations."
    "In the global context, India has emerged as one of the fastest-growing paint markets." = "Within this global framework, India stands out as a premier growth market. Valued at roughly INR 75,000 crores in the 2024-25 financial year, the Indian paint sector is projected to surpass the INR 1,00,000 crore mark (approximately USD 12 billion) by 2027-28, reflecting a robust double-digit CAGR between 10% and 12%. This exceptional trajectory has drawn significant institutional capital, highlighted by the aggressive entry of massive conglomerates like JSW Paints and Grasim Industries (Birla Opus), thereby heightening competition in a space historically controlled by legacy brands."
    "1. Decorative Segment: decorative paints are highly consumer-centric" = "Decorative Segment: Claiming a massive 74% to 75% market share, this consumer-driven category includes primers, distempers, wood finishes, and wall emulsions. It is heavily influenced by shortening repainting cycles, higher disposable incomes, and residential construction. Success in this tier depends on in-store tinting capabilities, widespread distribution, and strong brand equity."
    "2. Industrial Segment: industrial coatings involve technical specifications" = "Industrial Segment: Making up the remaining 25% to 26%, this B2B-oriented category covers protective coatings, coil coatings, marine finishes, powder coatings, and automotive paints. Growth is tied to industrial production and infrastructure scaling. Purchasing decisions here are dictated by bulk pricing agreements, technical specs, and rigorous product approvals."

    "Astral Chemie Limited (ACL) is a wholly-owned subsidiary of Astral Limited" = "Astral Chemie Limited (ACL) functions as a wholly-owned subsidiary of the prominent building materials giant, Astral Limited. The parent company officially entered the coatings arena in April 2022 by purchasing a 51% majority stake in Gem Paints Private Limited, a respected Bengaluru-based manufacturer of industrial and decorative paints founded by Mr. A.S. Gandotra in 1980. By September 2025, Astral successfully acquired the remaining equity, fully absorbing Gem Paints and rebranding the entity as Astral Chemie Limited. This strategic buyout allowed Astral to merge Gem Paints' four decades of manufacturing expertise with its own sprawling national distribution footprint."
    "Astral Chemie Ltd manufactures decorative paints, industrial coatings, and protective finishes" = "Operating under the brand names Gem Paints and Astral Paints, the company produces a wide array of protective finishes, industrial coatings, and decorative paints. The decorative line features premium wood finishes, putties, primers, and emulsions, while the industrial portfolio boasts the famous Gem Hammertone finishes alongside high-grade PU and protective coatings. Production is centered at advanced facilities in Bengaluru, which rely on stringent quality control protocols and automated batch processing. Astral's expansion into the paint sector is heavily bolstered by its existing, stellar reputation in the adhesives and piping markets."

    "Astral Chemie Limited (operating in the paint sector as Astral Coatings) was established with a focus" = "Originally, Astral Chemie Limited built its foundation by producing surface preparation compounds, construction chemicals, and specialized industrial adhesives. Recognizing the immense potential for growth and the natural supply chain synergies present in the coatings market, the organization strategically broadened its horizons. The company introduced a robust lineup of highly durable primers, exterior weather-resistant coatings, and interior emulsions under the Astral Coatings banner."
    "To accelerate its presence in South India, Astral Coatings integrated the regional manufacturing" = "To rapidly establish a foothold in Southern India, Astral integrated the established logistics networks and manufacturing hubs of Gem Paints. This critical acquisition provided Astral with instant access to a vast regional dealer network and fully operational production sites in Bangalore. By fusing Gem Paints' local market relationships with Astral's deep knowledge of polymer chemistry, the company transformed into a formidable regional contender. Today, Astral Chemie Ltd is highly regarded for its structured dealer support initiatives, its focus on non-toxic, water-based formulations, and its unwavering commitment to product excellence."

    "Astral Chemie Ltd Limited follows a divisional organizational structure, designed" = "Astral Chemie Limited utilizes a divisional corporate structure carefully crafted to blend Astral's marketing and sales prowess with the manufacturing operations of the legacy Gem Paints. The overarching corporate strategy is steered by the Board of Directors of Astral Limited, while daily operational management falls to the Managing Director of the coatings division. This hierarchy is specifically optimized to facilitate seamless channel coordination and sales management."
    
    "Manufacturing Operations Division: Manages production facilities, batch processing" = "Manufacturing Operations: Oversees quality control, raw material procurement, batch formulation, and facility management at the Doddaballapur plant."
    "Sales & Trade Marketing Division: Coordinates the sales force, executes promotional programs" = "Sales & Trade Marketing: Manages relationships with retail partners, executes promotional campaigns, and directs the regional sales force."
    "Channel Support & Logistics Division: Manages warehousing, transport logistics" = "Channel Support & Logistics: Handles digital portal administration, credit monitoring, depot operations, transport logistics, and warehousing."
    "Technical Services & Color Tinting Division: Manages automatic color mixing machines" = "Technical Services & Color Tinting: Coordinates technical training for dealers and maintains the network of automated in-store color mixing machines."

    "Astral Chemie Limited operates under the corporate governance framework of Astral Limited, focusing on innovation" = "Operating under the broader corporate umbrella of Astral Limited, Astral Chemie Limited is deeply committed to sustainable expansion, premium quality, and constant innovation."
    "Sustain Astral's position as a leading building materials provider in India through world-class performance" = "To maintain Astral's status as a premier provider of building materials in India by delivering cutting-edge paint solutions, forging resilient channel partnerships, and achieving world-class operational performance."
    "To create value for dealers and consumers by delivering high-quality coatings, promoting digital channel tools" = "To generate substantial value for both consumers and dealers by fostering long-term, transparent relationships, championing digital channel innovations, and consistently producing high-quality coatings."
}

$count = 0
foreach ($p in $doc.Paragraphs) {
    $text = $p.Range.Text
    foreach ($key in $replacements.Keys) {
        if ($text -match "^.?$key") {
            $rng = $p.Range
            $rng.MoveEnd(4, -1) | Out-Null
            $rng.Text = $replacements[$key]
            $count++
            break
        }
    }
}

Write-Output "Successfully replaced $count paragraphs."

$doc.Save()
$doc.Close()
$word.Quit()
