$word = New-Object -ComObject Word.Application
$word.Visible = $false
$doc = $word.Documents.Open('e:\Vishruth Reports\Yogeshwari\New folder\YO FINAL 12345678_formatted 123456.docx')

$replacements = @{
    "The rapid growth of the modern retail environment" = "India's rapidly expanding modern retail landscape has completely redefined how fast-moving consumer goods (FMCG) are marketed to end-users. As massive supermarkets and sprawling hypermarkets steadily replace traditional neighborhood grocers, physical store shelves have become the ultimate battleground for brand visibility. In this self-service ecosystem, visual aesthetics dictate purchasing outcomes."
    "This study examines the impact of store display" = "This academic inquiry investigates how strategic visual merchandising and organized store displays influence the sales volume of ITC products. Utilizing primary data gathered from shoppers at contemporary supermarkets in the Dharwad region, the research identifies which specific visual elements—such as lighting, shelf positioning, and promotional signage—most effectively capture consumer attention."
    "The analysis of the survey responses indicates a high" = "An evaluation of the collected survey data reveals that modern consumers are highly receptive to in-store visual cues. Shoppers overwhelmingly reported that organized, aesthetically pleasing product arrangements make it significantly easier to locate specific ITC products, thereby streamlining their overall shopping experience and increasing brand recall."
    "Furthermore, impulse buying behavior emerged as a primary" = "Additionally, the data confirms that robust visual merchandising directly fuels impulse purchasing. Strategic placements, such as highly visible end-cap displays and bulk discount zones near checkout counters, successfully tempt shoppers into buying unplanned items. Cross-merchandising—for example, placing ITC’s Sunfeast biscuits near coffee aisles—further accelerates this spontaneous buying behavior."
    "The research also addresses the challenges and negative aspects" = "Conversely, the study also highlights the severe financial penalties associated with poor retail execution. Shoppers identified empty shelves and stock-outs as major deterrents, frequently causing them to instantly switch to a competing brand. Cluttered aisles, missing price tags, and inadequate lighting also severely disrupt the purchasing journey, underscoring the absolute necessity of flawless inventory management."
    "Based on the findings of this research, several strategic" = "Drawing from these empirical results, several tactical recommendations are offered to optimize ITC’s retail footprint. Primarily, ITC must aggressively negotiate for premium, eye-level shelf space and high-traffic end-caps. Furthermore, implementing strict 'First-In, First-Out' (FIFO) restocking protocols will eliminate stale inventory and guarantee that fresh products are always visually prominent."
    "In conclusion, store display and visual merchandising play a critical" = "To summarize, superior visual merchandising and strategic store displays are indispensable tools for accelerating ITC product sales within modern retail channels. By flawlessly executing in-store promotions and maintaining immaculate shelf availability, ITC can maximize consumer engagement and secure a decisive competitive advantage in the crowded FMCG marketplace."
    "The Fast Moving Consumer Goods (FMCG) sector is the fourth" = "Ranking as the fourth largest segment of the Indian economy, the Fast-Moving Consumer Goods (FMCG) sector encompasses high-turnover, low-cost daily necessities such as packaged foods, toiletries, and household cleaners. This massive industry has witnessed explosive, continuous growth, fueled by rising middle-class incomes, rapid urban expansion, and the relentless proliferation of modern digital commerce networks."
    "The Indian FMCG market is divided into three main segments" = "Structurally, the domestic FMCG arena is categorized into three primary divisions: food and beverages (which dominate roughly half the market share), personal care, and home care. This environment is fiercely contested, featuring fierce battles between entrenched multinational giants like Hindustan Unilever and massive domestic powerhouses like ITC Limited and Britannia."
    "As the retail environment becomes more competitive, companies must shift" = "Given the intensifying retail competition, FMCG corporations are increasingly pivoting their marketing budgets away from traditional television advertising and toward point-of-sale activations. In self-service retail formats, shoppers make instantaneous decisions based entirely on visual product presentation, transforming shelf layouts into the most critical driver of market share."
    "Additionally, the rapid growth of digital media and e-commerce" = "Furthermore, the explosion of digital marketing and social media has drastically elevated consumer expectations. Today's highly informed shoppers demand impeccable packaging, verifiable hygiene standards, and instant product availability. Consequently, FMCG brands must ensure that their physical retail execution perfectly matches the premium image portrayed in their online advertising campaigns."
    "The rise of digital payments, quick commerce platforms, and direct" = "The advent of rapid delivery platforms (quick commerce) and direct-to-consumer (D2C) channels has further intensified the battle for consumer attention. With shoppers now able to procure daily goods via smartphone apps in minutes, physical retailers and brands must design highly immersive, tactile in-store experiences to prevent total digital cannibalization."
    "Each of these segments features unique consumer purchase patterns" = "Distinct consumer buying behaviors define each FMCG sub-segment. Packaged snacks and beverages are predominantly impulse buys, making them highly responsive to aggressive checkout-counter displays. Conversely, personal care items represent calculated, planned purchases where detailed ingredient labels, brand trust, and clear pricing information dictate the final selection."
    "FMCG manufacturers must deploy localized product positioning to match" = "To maximize sales, manufacturers must tailor their visual strategies to fit these behavioral profiles. While snack foods require vibrant, mouth-watering imagery to stimulate immediate hunger, personal hygiene products necessitate pristine, well-lit shelf spaces that subliminally communicate cleanliness, safety, and dermatological reliability."
    "Visual merchandising has emerged as a primary in-store marketing tool" = "Visual merchandising serves as the tip of the spear in modern retail marketing. Encompassing everything from window displays and aisle end-caps to promotional danglers and shelf-talkers, these visual elements are designed to arrest shopper attention. By dominating this visual space, FMCG brands can effectively hijack the consumer's purchasing journey."
    "Furthermore, modern retail chains leverage data analytics to optimize" = "Moreover, sophisticated retail chains now utilize advanced data analytics to scientifically optimize their floor plans. By analyzing foot traffic patterns and basket data, retailers collaborate with brands to design high-conversion promotional zones, ensuring that point-of-sale materials effectively highlight bundle offers and new product launches."
    "ITC Limited is one of India's foremost private sector conglomerates" = "Established originally in 1910 as the Imperial Tobacco Company, ITC Limited has evolved into one of India’s most prestigious and highly diversified private sector conglomerates. With a massive presence across FMCG, luxury hospitality, paperboards, and agribusiness, ITC is globally recognized for its robust financial performance and deep commitment to sustainable business practices."
    "ITC's FMCG division has emerged as a major growth engine" = "The FMCG division has rapidly become the central growth engine for ITC. Over the last twenty years, the conglomerate has successfully incubated and scaled over 25 distinct 'mother brands'—including household names like Aashirvaad, Sunfeast, Bingo!, and Classmate—securing dominant market leadership across multiple highly competitive categories."
    "ITC's commitment to sustainable business practices is reflected in its" = "ITC’s dedication to corporate sustainability is legendary within the global business community. The conglomerate holds the unique distinction of being carbon-positive, water-positive, and solid-waste recycling positive for over a decade, proving that massive industrial scale can successfully coexist with stringent environmental stewardship."
    "The historical transition of ITC from a single-product tobacco company" = "ITC’s strategic evolution from a legacy tobacco manufacturer into a multi-sector FMCG juggernaut is widely studied in corporate strategy circles. This diversification successfully insulated the company from severe regulatory crackdowns on tobacco while simultaneously unlocking massive new revenue streams in the fast-growing packaged foods and personal care sectors."
    "The e-Choupal program is one of ITC's key initiatives, designed to" = "Launched in 2000, the e-Choupal initiative remains one of ITC’s most celebrated strategic innovations. By deploying internet-connected kiosks in rural villages, this program directly links farmers to global agricultural markets, providing them with real-time weather forecasts, crucial pricing data, and modern farming techniques."
    "This platform allows farmers to sell their agricultural produce directly" = "The e-Choupal network empowers farmers to bypass traditional, exploitative middlemen and sell their crops directly to ITC. This disintermediation drastically reduces transaction costs, while simultaneously guaranteeing ITC a reliable, high-quality, and transparent supply of agricultural raw materials for its packaged food divisions."
    "Furthermore, the e-Choupal network serves as a channels for distributing" = "Beyond procurement, the e-Choupal kiosks function as vital two-way distribution channels. Through these rural hubs, ITC successfully markets essential agricultural inputs—such as high-yield seeds and fertilizers—as well as its own FMCG consumer products, deeply penetrating rural markets that are otherwise inaccessible."
    "This co-location strategy offers several benefits: it reduces product" = "ITC’s strategy of co-locating manufacturing units with massive logistical warehouses yields immense operational dividends. This integrated approach slashes transportation overhead, minimizes supply chain delays, and ensures strict quality control, allowing fresh products to reach retail shelves faster than competitors."
    "By combining manufacturing and warehousing operations, ICML hubs simplify" = "The Integrated Consumer Goods Manufacturing and Logistics (ICML) hubs streamline the entire supply chain. Because finished goods are seamlessly transferred from production lines directly into automated storage bays, ITC completely eliminates the costly intermediate handling steps that plague traditional distribution networks."
    "These hubs utilize computerized warehouse management systems (WMS) to track" = "These advanced ICML facilities are powered by state-of-the-art Warehouse Management Systems (WMS). Featuring automated sorting conveyors, barcode scanners, and robotic loading docks, these digital systems provide real-time inventory visibility, ensuring that localized stock-outs are immediately rectified without human intervention."
    "ITC is committed to delivering safe, reliable, and high-quality consumer" = "Uncompromising quality assurance is the bedrock of ITC’s manufacturing philosophy. Every single food processing facility and production unit strictly adheres to international certifications (such as ISO 22000 and HACCP), ensuring that every consumer product meets the highest global standards for safety, hygiene, and reliability."
}

$count = 0
foreach ($p in $doc.Paragraphs) {
    $text = $p.Range.Text.Trim()
    foreach ($key in $replacements.Keys) {
        if ($text.StartsWith($key)) {
            $rng = $p.Range
            $rng.MoveEnd(4, -1) | Out-Null
            $rng.Text = $replacements[$key]
            $count++
            break
        }
    }
}

Write-Output "Successfully replaced $count paragraphs in Chapters 1-2."

$doc.Save()
$doc.Close()
$word.Quit()
