$word = New-Object -ComObject Word.Application
$word.Visible = $false
$doc = $word.Documents.Open('e:\Vishruth Reports\Astral_Coatings_Dealer_Relationship_Report_11_expanded.docx')

$replacements = @{
    "Despite the extensive literature on supply chain management, retail logistics, and consumer buying" = "Although academic research heavily covers retail logistics and broad supply chain dynamics within the home improvement arena, there is a glaring lack of targeted empirical studies focusing on B2B dealer relationship management (DRM) specifically within the coatings sector. Traditional relationship marketing frameworks frequently highlight service quality and mutual trust, but they routinely ignore the highly specialized operational realities of paint retail. Retail paint dealers face unique challenges, such as operating expensive automated tinting equipment, juggling vast stocks of liquid colorants and neutral bases, and navigating complex credit arrangements with competing manufacturers. Additionally, previous literature seldom investigates how modern interventions—like B2B digital ordering platforms, specialized relationship managers, and collaborative contractor events—shape a dealer's brand advocacy. Within the regional Indian market, the dealer functions as a critical gatekeeper who strongly influences consumer decisions, especially where brand loyalty is weak. Consequently, this study aims to fill these literature voids by thoroughly analyzing how various DRM components—including logistics, incentive schemes, credit support, and communication—impact overall dealer satisfaction and brand loyalty. By analyzing a primary dataset of 301 dealers in the Dharwad area, this paper provides actionable, strategic insights specifically tailored for Astral Coatings."
    "The foundational Commitment-Trust Theory of Relationship Marketing, originally posited by Morgan" = "Morgan and Hunt's (1994) seminal Commitment-Trust Theory of Relationship Marketing continues to serve as a vital framework in modern B2B environments. Nevertheless, contemporary scholars have modernized this theory by integrating digital factors. For instance, a comprehensive meta-analysis by Palmatier et al. (2021) across various manufacturing industries revealed that while face-to-face interpersonal trust is still essential, 'Systemic Trust' has emerged as a crucial driver of long-term loyalty. Systemic trust refers to the dependability and clarity of a manufacturer’s digital billing and ordering platforms. Notably, their findings demonstrated that optimizing these digital metrics—especially regarding automated discount calculations—can slash channel conflicts by up to 40%."
    "In the specific context of the building materials and coatings industry, Sharma and Iyer" = "Examining the coatings and building materials sector specifically, Sharma and Iyer (2022) investigated the concept of 'Channel Power Asymmetry.' Because the Indian paint industry is traditionally dominated by a few massive players, these top-tier companies often force dealers into restrictive credit agreements and heavy inventory burdens. However, Sharma and Iyer's research revealed that emerging challenger brands—such as Astral Coatings—can effectively counter this dynamic through 'Relational Flexibility.' By tailoring credit terms to match seasonal fluctuations rather than enforcing strict corporate policies, brands can win significant favor. Their empirical data proved that dealers become much stronger brand advocates when manufacturers supply flexible financial support during slow periods, such as the monsoon season."
    "A critical mass of recent literature focuses on the digitalization of the B2B supply chain" = "An increasing volume of contemporary research centers on the digital transformation of B2B supply chains. In their 2023 study, Kumar and Singh analyzed the uptake of Sales Force Automation (SFA) platforms among paint and hardware retailers in India’s tier-2 and tier-3 cities, uncovering a prominent 'Digital Divide.' Even as manufacturers heavily promote mobile ordering applications to cut processing overhead, veteran dealers frequently push back against these technologies, preferring traditional, relationship-driven manual ordering due to limited digital fluency. The authors concluded that to prevent alienating their retail partners, manufacturers must pair their technological rollouts with dedicated relationship managers who serve as guides to smoothly transition dealers onto digital platforms."
    "Furthermore, research by Desai, R. (2024) highlighted the operational impact of 'Just-In-Time'" = "Adding to this, Desai's (2024) research emphasized how 'Just-In-Time' (JIT) delivery systems directly influence a retailer's bottom line. By analyzing the holding costs related to in-store tinting machines, Desai found that dealers experience a massive boost in inventory turnover since they only need to store compact colorant cartridges and neutral bases instead of countless pre-mixed buckets. However, this high-velocity model is incredibly vulnerable; a dealer will instantly lose a sale if the manufacturer's regional warehouse delays a tinting base delivery by even 24 hours. Desai’s simulated models definitively established that logistical reliability dictates the absolute ceiling for retail sales; dealers will abandon brands that fail to restock quickly, no matter how lucrative their discount schemes might be."
    "The unique triadic relationship (Manufacturer-Dealer-Painter) in the coatings sector has garnered" = "Recently, academics have begun focusing on the complex, three-way dynamic between the manufacturer, the dealer, and the painter. A detailed 2022 field study by Venkatraman explored the success rates of Painter Loyalty Programs (PLPs). While dealers traditionally managed these programs, manufacturers now run them directly using mobile QR-code scanning technologies. Venkatraman’s findings indicated that although direct manufacturer-to-painter apps successfully build applicator loyalty, they simultaneously risk causing 'Dealer Disenfranchisement' by cutting the retailer out of the loop. To maximize success, the study recommends implementing DRM strategies where painter rewards must be validated by the dealer, ensuring the retailer remains an indispensable part of the local trade community."
    "Finally, literature surrounding corporate social responsibility (CSR) in B2B channels suggests" = "Lastly, recent academic discourse regarding corporate social responsibility (CSR) within B2B channels highlights a stark shift toward ethical supply chains. In a 2023 analysis, Patel revealed that urban dealers are heavily prioritizing a manufacturer’s ecological footprint—such as lead-free certifications and zero-VOC formulations—when choosing what to stock. This shift is primarily driven by heightened consumer awareness surrounding indoor air quality and toxicity. This data indicates that Astral’s dedication to eco-friendly, green chemistry is far more than a simple marketing pitch; it is a fundamental strategic asset for securing retail shelf space and driving dealer loyalty."
}

$count = 0
foreach ($p in $doc.Paragraphs) {
    $text = $p.Range.Text
    foreach ($key in $replacements.Keys) {
        if ($text -match "^.?$key") {
            $rng = $p.Range
            $rng.MoveEnd(4, -1) | Out-Null
            $rng.Text = $replacements[$key]
            $count++
            break
        }
    }
}

Write-Output "Successfully replaced $count paragraphs in Chapter 3."

$doc.Save()
$doc.Close()
$word.Quit()
